### ISSUE TITLE
LowerBoundValue-property of IfcPropertyBoundedValue returns upper bound

### ISSUE THREAD

**Issue by Tharn83** [GeometryGym/GeometryGymIFC#21]
The property 'LowerBoundValue' of the class 'IfcPropertyBoundedValue' in the 'GeometryGymIFC'-project returns the field 'mUpperBoundValue' instead of 'mLowerBoundValue'.

**Comment by jmirtsch** [comment]
Thanks for bringing this to my attention, it's now fixed in the WorkInProgress branch and I will release an update ASAP.
