### ISSUE TITLE
IfcTrapeziumProfileDef

### ISSUE THREAD

**Issue by sheblykin** [GeometryGym/GeometryGymIFC#30]
Add in class IfcTrapeziumProfileDef
 
public double BottomXDim { get => mBottomXDim; set => mBottomXDim = value; }
public double TopXDim { get => mTopXDim; set => mTopXDim = value; }
public double YDim { get => mYDim; set => mYDim = value; }
public double TopXOffset { get => mTopXOffset; set => mTopXOffset = value; }

**Comment by jmirtsch** [comment]
Thanks, I have pushed a commit to the WorkInProgress branch with these properties added.
Note that to allow as many users to use the toolkit as possible, I have been targeting dotnet4.5 and c# 6.0.
Hence the older style of getters and setters.

I have also been developing methods to generate and check the toolkit against the IFC specification so hopefully will fix any other outstanding properties in the near future.  Thanks for reporting this.

**Comment by sheblykin** [comment]
good day
I noticed one feature after merge ifc files
one ifcslab is lost
[2-slab.zip](https://github.com/GeometryGym/GeometryGymIFC/files/4984834/2-slab.zip)

elements get List<IfcBuiltElement> elements = project.Extract<IfcBuiltElement>();
if (element is IfcSlab slab)

**Comment by jmirtsch** [comment]
Your file uses the same GlobalId ( 3Ohocf4Ln9futPiBQDjTWZ ) in each slab, this isn't valid.
Our extract method ensures a unique set is returned using GlobalId as a key.

**Comment by sheblykin** [comment]
thanks
