### ISSUE TITLE
Typo exporting an IfcOpenCrossProfileDef instance

### ISSUE THREAD

**Issue by seb-esser** [GeometryGym/GeometryGymIFC#31]
Creating an instance of [IfcOpenCrossProfileDef](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcopencrossprofiledef.htm) using: 
`var profileDef = new IfcOpenCrossProfileDef(db, "profileName", true, new List<double>{2.0, 3.5}, new List<double>{0.1, 0.2});`
_Constructor in GeometryGymIfc.IFC.Core.IFC O.cs line 707_
results in:
`#18= IFCOPENCROSSPROFILEDEF(.AREA.,'profileName',.T.,(2.0,3.5),(0.1,0.2),(#));` .

As I haven't set any tag list for the last attribute of IfcOpenCrossProfileDef, I would expect a nulled attribute value marked with `$` instead of `(#)`

Did I miss something from the STEP side of things @pjanck ?

**Comment by jmirtsch** [comment]
Thanks for reporting this bug.  I've just made a correction in the latest commit (including nuget package).  Let me know if it's still amiss or if you find anything else amiss.

**Comment by seb-esser** [comment]
thanks for the fix. looks good now!
`#11= IFCOPENCROSSPROFILEDEF(.AREA.,'test',.T.,(2.0,2.4),(0.1,0.2),$);`

Cheers, 
Sebastian
