### ISSUE TITLE
IfcAnnotation class has no PredefinedType available

### ISSUE THREAD

**Issue by seb-esser** [GeometryGym/GeometryGymIFC#32]
I am missing the PredefinedType for IfcAnnotation according to [IFC4x3 Documentation](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcannotation.htm) in https://github.com/GeometryGym/GeometryGymIFC/blob/bce4fe19d864fd06981cdc71d039cb40e18aa9c0/Core/IFC/IFC%20A.cs#L596 

I've just checked the repo quickly and am working on the Nuget package right now. Likely, I have overseen something or missed the latest WIP commit in my current test project.

**Comment by jmirtsch** [comment]
Thanks, that's certainly a bug.  I've just made a commit to fix this and will publish a nuget package after you've tested.
I have been working on a utility to test the toolkit against a schema spec, but I still need to finish it to identify changes such as this.

**Comment by seb-esser** [comment]
Thanks Jon, looks perfectly fine now. I'll push another example to the sample repo soon
