### ISSUE TITLE
OutOfMemoryException when creating DatabasIfc

### ISSUE THREAD

**Issue by errone92** [GeometryGym/GeometryGymIFC#33]
Hello Jon,

I have an IFC2X3 file that I am trying to use in a WPF application I am developing. when creating a new DatabasIfc with the filename I get a System.OutOfMemoryException (see below)

![image](https://user-images.githubusercontent.com/46051037/93214194-243daa00-f765-11ea-9d1c-07a3f759d44c.png)

However, when I was first testing this application as a Console App it worked fine. I also have the same file in IFC4 version and it works fine. I have tried it both async and normally. Any Idea why this is happening?

**Comment by jmirtsch** [comment]
The Async file read is a new feature (I was having to process some large ifc files and was motivated to improve file reading speed).
But I have been testing it on these files and not had this error occur.

If there is any chance to share the problematic file to me (privately is fine), I'll certainly try it myself.  Is it a really large file?
