### ISSUE TITLE
IFC4x3: IfcBuiltElement is not instantiable

### ISSUE THREAD

**Issue by seb-esser** [GeometryGym/GeometryGymIFC#35]
Due to [IFC4x3: IfcBuiltElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcbuiltelement.htm) IfcBuiltElement should be instantiable. 

I was trying `var myProduct = new IfcBuiltElement(database);`, which seems valid looking on the constructor declarations. However, Visual Studio is telling me that I cannot instantiate this class due to the protection level. Nevertheless, IfcBuildingElementProxy is still available when drafting an IFC4x3_RC1 based model. Likely IfcBuildingElementProxy misses the deprecated flag.

Thanks - let me know if I can support anything else than just reporting issues I am spotting during my testing sessions

**Comment by jmirtsch** [comment]
Hi Sebastian,

Thanks for reporting, I just pushed to the work in progress branch with public constructors for the class as it's no longer abstract.

The toolkit as you know supports multiple versions, so I haven't necessarily removed constructors for deprecated (or deleted) concepts, but I have usually put an Obsolete attribute on the class (or attribute) to at least provide some feedback to code calling it.

**Comment by seb-esser** [comment]
Yep, thanks! 
The obsolete attribute is perfect and makes cross-versioning quite convenient
