### ISSUE TITLE
Cannot create an IfcCompositeCurve without arguments

### ISSUE THREAD

**Issue by hu-stefan** [GeometryGym/GeometryGymIFC#38]
I´m trying to create an `IfcAlignmentHorizontal` there for i need an `IfcCompositeCurve`. 
But unfortunately its not possible to create an  `IfcCompositeCurve` without arguments.
Is there a another way to create it for this special case?

![code](https://user-images.githubusercontent.com/65392561/102716993-c2e72300-42df-11eb-8a08-de7a232e2173.jpg)

I´m using v0.1.06 atm.
thank you in advance

**Comment by jmirtsch** [comment]
The basecurve parameter of type IfcCompositeCurve is generated in the alignment horizontal constructor.
So it will be constructed in the code of the alignmenthorizontal constructor.
It should work if you change the top line to this:

IfcCompositeCurve basecurve = null;

I haven't checked if you can use a dynamic type using keyword var

**Comment by hu-stefan** [comment]
I see. Thanks for the fast support.
