### ISSUE TITLE
Possibility to remove entries from DatabaseContainer

### ISSUE THREAD

**Issue by hu-stefan** [GeometryGym/GeometryGymIFC#40]
Hi there,

I try to change the base beometry of a BuildingElemntProxy.
First i add an RectangleProfile, but later i want to update the RectangleProfile into an CircleProfile.
So i end up with an orphaned RectangleProfile. Is it possible to remove this entry from the database container?

My coding:
![Screenshot 2021-01-21 152522](https://user-images.githubusercontent.com/65392561/105364337-596b7480-5bfd-11eb-991c-7637144680a5.jpg)
 

best regards
Stefan

**Comment by jmirtsch** [comment]
There are two strategies for handling this.

The first strategy for removing identified orphaned elements is a method called "Dispose".
This has an argument for whether to also call on the dispose method for nested attributes (ie if the profile is an arbitrary profile, to call dispose on the curve(s) that define it).

This can get a bit tricky if there are common references to a nested attribute.

The alternative strategy is to "duplicate" the project entity.  This will generate a new IFC database anew, and only live entities in the hierarchy will get duplicated, anything orphaned will be filtered out.  This is a preferred method, but I'm wondering if some aspects of this might be in the closed source portion of the toolkit.  If you try it and have problems, let me know and I'll review and improve it.

**Comment by hu-stefan** [comment]
Ah thank you!
The first one works perfect.
