### ISSUE TITLE
Error when reading a file that contains empty lines via stream

### ISSUE THREAD

**Issue by bschorno** [GeometryGym/GeometryGymIFC#41]
I have an IFC step file with empty lines e.g. after the header section or between the tags in the data section. When I read it via textstream it causes an error in `SerializationIfcSTEP->ReadStepStream`

![grafik](https://user-images.githubusercontent.com/20213616/106116136-d9d82b00-6151-11eb-9b28-638171851091.png)

**Comment by jmirtsch** [comment]
Thanks for reporting this.  I've just pushed a commit to the WorkInProgress branch that should resolve this.  Let me know if you test it and still have problems.

**Comment by bschorno** [comment]
Thank you for the fast reply.
The case on the screenshot work's now but I think there is still an issue when the step file has empty lines in the data section between the tags
If also created a pull request where I fixed this problem, maybe you can check it out and merge. #42 

Also in my pull request is a fix where the wrong string will be added to the list. I think it should be `lines.add(str);`
https://github.com/GeometryGym/GeometryGymIFC/blob/a2863e13bdfc981dd5dc9ce27d58506da584c338/Core/IFC/DatabaseIFC.cs#L1841-L1853

**Comment by jmirtsch** [comment]
Thank you for the pull request and contributing to this project.

The changes look good, and I have merged them.
