### ISSUE TITLE
IfcReal set Value FormatException

### ISSUE THREAD

**Issue by bschorno** [GeometryGym/GeometryGymIFC#47]
There is an FormatException when setting a decimal to the `IfcReal.Value`. I think the setter should use `Convert.ToDouble` instead of `Convert.ToInt32`

![grafik](https://user-images.githubusercontent.com/20213616/112013582-6d165700-8b2a-11eb-9045-bd0197cb3531.png)

**Comment by jmirtsch** [comment]
Thanks, that certainly looks wrong.  I've just changed it in my code and will push in the next version.
