### ISSUE TITLE
Unrecognized format! exception

### ISSUE THREAD

**Issue by simonedd** [GeometryGym/GeometryGymIFC#61]
Hi everyone,

I have a file that throws an "Unrecognized format!" exception in the ParserSTEP.StripListLink method on the following line
`#16 = IFCPROJECT('0y9Aqf8xv0Jho7Y5Dfqn2E', $, 'Projekt', $, $, $, $, #17, #1);`
I think the round brackets are missing around the #17 field.
Is it really a bad format or a bug? Is it possible to handle this case? Other readers can parse the file correctly.

Thanks,
Simone

**Comment by jmirtsch** [comment]
Yes, the second last field should be a set of contexts, and wrapped with brackets to indicate this.  ie
#13= IFCPROJECT('1cSjcDqWPBUgfg7n0bR5xM',$,'Grasshopper Project',$,$,$,$,(#25),#14);
Our toolkit does work around some common serialization issues, but every extra check slows down the experience
for valid files.  What software is authoring the non compliant line?  Is it practical to expect them to correct this?
Click on Attribute Inheritance here https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcproject.htm

**Comment by simonedd** [comment]
The file is from mh-software, but I'm not in touch directly with them. Maybe the brackets can be omitted if there is only one element in the set? Otherwise is not a big deal don't handle this, I have just one file with this issue.
