### ISSUE TITLE
IfcTrimmingSelect ParameterValue

### ISSUE THREAD

**Issue by simonedd** [GeometryGym/GeometryGymIFC#62]
Hi,

The parsing of IFCPARAMETERVALUE fails if there is a white space in the line definition. Is it possible to fix it?
`#12891 = IFCTRIMMEDCURVE (#12890, (IFCPARAMETERVALUE (270.)), (IFCPARAMETERVALUE (90.)), .F., .PARAMETER.);`

Thanks,
Simone

**Comment by jmirtsch** [comment]
Thanks, yes the existing code doesn't handle intermediate spaces very well.
I have made a change to improve it.  https://github.com/GeometryGym/GeometryGymIFC/commit/c88dc9948f835736ed4601fcb028847282c56c24
It will be included in the next build.

**Comment by simonedd** [comment]
It works. Thanks
