### ISSUE TITLE
A hello world

### ISSUE THREAD

**Issue by GildedHonour** [GeometryGym/GeometryGymIFC#73]
I need a simple example of generating ifc file.
Is there any?

**Comment by jmirtsch** [comment]
You can find some sample code for generating IFC data sets or extracting information from existing at this repository.
https://github.com/GeometryGym/GeometryGymIFCExamples/blob/master/ConsoleCreateWall/Program.cs

**Comment by GildedHonour** [comment]
@jmirtsch  How to generate an IFC file itself out of that code?

**Comment by jmirtsch** [comment]
There is a method WriteFile on the databaseifc class that has a file path as a parameter to write to file.
