### ISSUE TITLE
Blanks lost in originating_system field of FILE_NAME header data

### ISSUE THREAD

**Issue by lorenzo-montesi** [GeometryGym/GeometryGymIFC#80]
When parsing header data, the originating_system field of FILE_NAME, which is a string, loses all spaces between words.
Furthermore, only timestamps and origining_system are parsed (e.g. author and organization are not)

**Comment by jmirtsch** [comment]
Thanks, I'm improving header parsing and retention as per this request. https://github.com/GeometryGym/GeometryGymIFC/discussions/79
I should have an implementation soon.

**Comment by jmirtsch** [comment]
I've revised the code in supporting a new attribute on the database storing STEP file header information.
Refer here and let me know if you have any feedback for further improvements.
https://github.com/GeometryGym/GeometryGymIFC/blob/09a0f173b59312bb9c548da8c61eb7677eaf0dde/Core/STEP/DatabaseSTEP.cs#L40

**Comment by lorenzo-montesi** [comment]
For me it's perfect. Thank you
