### ISSUE TITLE
About IEnumerable<IEnumerable<IfcCartesianPoint>>

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [GeometryGym/GeometryGymIFC#81]
When initialize the IfcBSplineSurface, how can the 'IEnumerable<IEnumerable<IfcCartesianPoint>>'  be initialzed

**Comment by jmirtsch** [comment]
Something like this can create a b spline surface (I didn't validate the values are legitimate).

`List<List<IfcCartesianPoint>> controlPoints = new List<List<IfcCartesianPoint>>();
List<IfcCartesianPoint> points = new List<IfcCartesianPoint>();
points.Add(new IfcCartesianPoint(db, 0, 0, 0));
points.Add(new IfcCartesianPoint(db, 1, 0, 0));
controlPoints.Add(points);
points = new List<IfcCartesianPoint>();
points.Add(new IfcCartesianPoint(db, 0, 1, 0));
points.Add(new IfcCartesianPoint(db, 1, 1, 0));
controlPoints.Add(points);

List<int> uMults = new List<int>() { 1, 1 }, vMults = new List<int>() { 1, 1 };
List<double> uKnots = new List<double>() { 0, 1 }, vKnots = new List<double>() { 0, 1 };

IfcBSplineSurfaceWithKnots surfaceWithKnots = new IfcBSplineSurfaceWithKnots(1, 1, controlPoints, uMults, vMults, uKnots, vKnots, IfcKnotType.UNIFORM_KNOTS);
`

**Comment by SHAWNZHANGSH** [comment]
Thanks, jmirtsch
