### ISSUE TITLE
About the IfcClosedShell

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [GeometryGym/GeometryGymIFC#82]
Hi, If a number of different types of facets are instantiated, how to add them to the same closded shell bellow.
IfcClosedShell(IEnumerable<IfcFace> faces) .

**Comment by SHAWNZHANGSH** [comment]
Maybe add surfaces to the IfcSurface list is a good idea

**Comment by jmirtsch** [comment]
You can add or revise the faces after the constructor.  Something like this:

List<IfcFace> faces = new List<IfcFace>();
IfcClosedShell closedShell = new IfcClosedShell(faces);
closedShell.CfsFaces.Add(new IfcFace(xxx));
