### ISSUE TITLE
Defined Class missed attributes

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [GeometryGym/GeometryGymIFC#93]
Hi, the IfcPropertyTableValue maybe miss its attribute in the Version 0.1.24.0.

#region Assembly GeometryGymIFCcore, Version=0.1.24.0

namespace GeometryGym.Ifc
{
    public class IfcPropertyTableValue : IfcSimpleProperty
    {
        public IfcPropertyTableValue(DatabaseIfc db, string name);

        protected override string BuildStringSTEP(ReleaseVersion release);
    }
}

**Comment by jmirtsch** [comment]
Thanks for reporting this.  You are correct.  I've just pushed a commit with this added (and other improvements).
https://github.com/GeometryGym/GeometryGymIFC/commit/85b64afcbe6468e3417ba666ed71805a55272807

If you are using nuget, let me know and I will publish a new version soon.

Thanks,

Jon
