### ISSUE TITLE
IfcStrucuturalLoadConfiguration

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [GeometryGym/GeometryGymIFC#94]
Hi, I find a problem when I initialize the IfcStrucuturalLoadConfiguration (which should be inherited from object),
which is show below.

Could you give me an example to achieve it?

![image](https://github.com/GeometryGym/GeometryGymIFC/assets/73410751/cd1769b1-f1a0-497d-9c9c-a2cad5b70059)

Best regard

**Comment by jmirtsch** [comment]
I'm sorry, I'm short on time at the moment to provide an example of this for free.
Structural analysis model inclusion in IFC remains rare at this point.  IfcStructuralLoadConfiguration does not inherit from IfcObject.  

There is an example file here that can provide some clues on how to assign loads, https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/structural-curve-member.htm

If you have problems, please contact me directly about technical support. If you wish to put together an example that can be publicly shared for other users, I can help review it and refine it.

**Comment by SHAWNZHANGSH** [comment]
Hi, according to the example above, firstly the IfcStructuralReaction needs to be initialized. 
However, there are some issues with the following code.
What methods can be used to solve this problem?

![image](https://github.com/GeometryGym/GeometryGymIFC/assets/73410751/5be39882-5f58-46fb-bab7-5ea31d6e4673)
![image](https://github.com/GeometryGym/GeometryGymIFC/assets/73410751/5a8bbcad-9238-4b46-9f64-c18bdf08b8a9)

**Comment by jmirtsch** [comment]
Thanks again for the report, IfcStructuralPointReaction was missing a public constructor.
I've just pushed a commit with this improved, and it will be available in the next nuget publish.

**Comment by SHAWNZHANGSH** [comment]
Thank you very much, Mirtschin.
May I ask when the updated source code would be available? 
Maybe I can compile the code myself instead of NuGet.

(＾▽＾)
Best regard

**Comment by jmirtsch** [comment]
Sure, sorry I see I didn't push the commit yesterday.  You should be to rebuild the dll now.
