### ISSUE TITLE
Readonly

### ISSUE THREAD

**Issue by SHAWNZHANGSH** [GeometryGym/GeometryGymIFC#95]
Hi , I found the attribute "HasResults" is read only. 
Is it possible to attach value for initialize the IfcStructuralAnalysisModel.

![image](https://github.com/GeometryGym/GeometryGymIFC/assets/73410751/5c75d7c9-edd9-4fea-81c3-939bb1e3436d)

Best regard

**Comment by jmirtsch** [comment]
The attributes of a set or list nature intentionally have setters only, some have collection change events subscribed to them.
You can't then append a group within the constructor.  I'd suggest you add the group to the attribute in a line below as per this:
IfcStructuralAnalysisModel model = new IfcStructuralAnalysisModel( ... );
model.HasResults.Add(ifcStructuralResultGroup);
